# Generated by Django 5.2.17 on 2026-09-22 14:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_city', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Enter a valid two-letter uppercase country code.', regex='^[A-Z]{2}$')])),
                ('provider_location_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feels_like', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('pressure', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('condition', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_readings',
                'ordering': ['-observed_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['country_code', 'city'], name='weather_location_idx'), models.Index(fields=['-observed_at'], name='weather_observed_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('humidity__gte', 0), ('humidity__lte', 100)), name='weather_humidity_range'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='weather_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='weather_longitude_range'), models.CheckConstraint(condition=models.Q(('pressure__gte', 1)), name='weather_positive_pressure'), models.CheckConstraint(condition=models.Q(('wind_speed__gte', 0)), name='weather_nonnegative_wind')],
            },
        ),
    ]
